/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author erick
 */
public class Principal extends javax.swing.JFrame {

    DefaultTableModel dtm;
    DefaultTableModel ptm;
    Object[] o = new Object[5];
    Object[] part = new Object[3];
    int filaSeleccionada = -1;
    
    /**
     * Creates new form jFramePrincipal
     */
    public Principal() {
        initComponents();
        dtm = (DefaultTableModel) tabla_procesos.getModel();
        ptm = (DefaultTableModel) tabla_particiones.getModel();
        
        txt_quantumRR.setEnabled(false);
        textField_QuantumColaAlta.setEnabled(false);
        textField_QuantumColaMedia.setEnabled(false);
        
        setTitle("Simulador SO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanelTabs = new javax.swing.JTabbedPane();
        jPanelMemoria = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_particiones = new javax.swing.JTable();
        panel_configuracionMemoria = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tamMemoria = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel_tamparticion = new javax.swing.JLabel();
        tamParticion = new javax.swing.JTextField();
        btn_addParticion = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        radiobtn_variables = new javax.swing.JRadioButton();
        radiobtn_fijas = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        radiobtn_firstfit = new javax.swing.JRadioButton();
        radiobtn_bestfit = new javax.swing.JRadioButton();
        radiobtn_worstfit = new javax.swing.JRadioButton();
        panej_gantt = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelAlgoritmos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        radioBtn_fcfs = new javax.swing.JRadioButton();
        radioBtn_roundRobin = new javax.swing.JRadioButton();
        label_RR = new javax.swing.JLabel();
        radioBtn_Prioridades = new javax.swing.JRadioButton();
        txt_quantumRR = new javax.swing.JTextField();
        textField_QuantumColaMedia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        textField_QuantumColaAlta = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        radioBtn_colasMultinivel = new javax.swing.JRadioButton();
        jRadiobtn_sjf = new javax.swing.JRadioButton();
        jPanelProcesos = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_procesos = new javax.swing.JTable();
        jBtn_addProceso = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTxt_tamanio = new javax.swing.JTextField();
        jTxt_tiempoArribo = new javax.swing.JTextField();
        jTxt_cicloVida = new javax.swing.JTextField();
        jBox_prioridad = new javax.swing.JComboBox<>();
        jBtn_deleteRow = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Archivo = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(876, 567));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jLabel6.setFont(new java.awt.Font("Garuda", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Particiones");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tabla_particiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Particion", "Tam. Memoria", "Dir. Comienzo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_particiones);
        if (tabla_particiones.getColumnModel().getColumnCount() > 0) {
            tabla_particiones.getColumnModel().getColumn(0).setResizable(false);
            tabla_particiones.getColumnModel().getColumn(1).setResizable(false);
            tabla_particiones.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_configuracionMemoria.setBackground(new java.awt.Color(102, 102, 102));
        panel_configuracionMemoria.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Tamaño de memoria:");

        tamMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamMemoriaActionPerformed(evt);
            }
        });
        tamMemoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tamMemoriaKeyTyped(evt);
            }
        });

        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("KB");

        jLabel_tamparticion.setForeground(java.awt.Color.white);
        jLabel_tamparticion.setText("Tamaño de particion:");

        tamParticion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamParticionActionPerformed(evt);
            }
        });
        tamParticion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tamParticionKeyTyped(evt);
            }
        });

        btn_addParticion.setForeground(java.awt.Color.black);
        btn_addParticion.setText("Agregar");
        btn_addParticion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addParticionMouseClicked(evt);
            }
        });
        btn_addParticion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addParticionActionPerformed(evt);
            }
        });
        btn_addParticion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btn_addParticionKeyTyped(evt);
            }
        });

        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Tipo de particionamiento:");

        buttonGroup1.add(radiobtn_variables);
        radiobtn_variables.setForeground(java.awt.Color.white);
        radiobtn_variables.setText("Variables");
        radiobtn_variables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtn_variablesActionPerformed(evt);
            }
        });

        buttonGroup1.add(radiobtn_fijas);
        radiobtn_fijas.setForeground(new java.awt.Color(255, 255, 255));
        radiobtn_fijas.setText("Fijas");
        radiobtn_fijas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        radiobtn_fijas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtn_fijasActionPerformed(evt);
            }
        });

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Algoritmo de Intercambio:");

        buttonGroup2.add(radiobtn_firstfit);
        radiobtn_firstfit.setForeground(java.awt.Color.white);
        radiobtn_firstfit.setText("First-Fit");
        radiobtn_firstfit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtn_firstfitActionPerformed(evt);
            }
        });

        buttonGroup2.add(radiobtn_bestfit);
        radiobtn_bestfit.setForeground(java.awt.Color.white);
        radiobtn_bestfit.setText("Best-Fit");

        buttonGroup2.add(radiobtn_worstfit);
        radiobtn_worstfit.setForeground(java.awt.Color.white);
        radiobtn_worstfit.setText("Worst-Fit");

        javax.swing.GroupLayout panel_configuracionMemoriaLayout = new javax.swing.GroupLayout(panel_configuracionMemoria);
        panel_configuracionMemoria.setLayout(panel_configuracionMemoriaLayout);
        panel_configuracionMemoriaLayout.setHorizontalGroup(
            panel_configuracionMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_configuracionMemoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_configuracionMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(panel_configuracionMemoriaLayout.createSequentialGroup()
                        .addComponent(radiobtn_variables)
                        .addGap(18, 18, 18)
                        .addComponent(radiobtn_fijas))
                    .addComponent(radiobtn_worstfit)
                    .addComponent(jLabel5)
                    .addComponent(radiobtn_firstfit)
                    .addComponent(radiobtn_bestfit)
                    .addGroup(panel_configuracionMemoriaLayout.createSequentialGroup()
                        .addGroup(panel_configuracionMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_tamparticion)
                            .addGroup(panel_configuracionMemoriaLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_configuracionMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tamParticion, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(tamMemoria))))
                        .addGap(18, 18, 18)
                        .addGroup(panel_configuracionMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(btn_addParticion))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        panel_configuracionMemoriaLayout.setVerticalGroup(
            panel_configuracionMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_configuracionMemoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_configuracionMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tamMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_configuracionMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_tamparticion)
                    .addGroup(panel_configuracionMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tamParticion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_addParticion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_configuracionMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radiobtn_variables)
                    .addComponent(radiobtn_fijas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radiobtn_firstfit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radiobtn_bestfit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radiobtn_worstfit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panej_gantt.setBackground(new java.awt.Color(102, 102, 102));
        panej_gantt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        javax.swing.GroupLayout panej_ganttLayout = new javax.swing.GroupLayout(panej_gantt);
        panej_gantt.setLayout(panej_ganttLayout);
        panej_ganttLayout.setHorizontalGroup(
            panej_ganttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 902, Short.MAX_VALUE)
        );
        panej_ganttLayout.setVerticalGroup(
            panej_ganttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        jLabel1.setText("Diagrama de Gantt");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panel_configuracionMemoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(panej_gantt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_configuracionMemoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panej_gantt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelMemoriaLayout = new javax.swing.GroupLayout(jPanelMemoria);
        jPanelMemoria.setLayout(jPanelMemoriaLayout);
        jPanelMemoriaLayout.setHorizontalGroup(
            jPanelMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMemoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanelMemoriaLayout.setVerticalGroup(
            jPanelMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMemoriaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTabs.addTab("Memoria", jPanelMemoria);

        jLabel7.setText("Algoritmos de planificacion");

        buttonGroup1.add(radioBtn_fcfs);
        radioBtn_fcfs.setText("First-Come,First-Served (FCFS)");
        radioBtn_fcfs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                radioBtn_fcfsMousePressed(evt);
            }
        });
        radioBtn_fcfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtn_fcfsActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioBtn_roundRobin);
        radioBtn_roundRobin.setText("Round Robin");
        radioBtn_roundRobin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                radioBtn_roundRobinMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                radioBtn_roundRobinMouseReleased(evt);
            }
        });

        label_RR.setText("Quantum");

        buttonGroup1.add(radioBtn_Prioridades);
        radioBtn_Prioridades.setText("Prioridades (cooperativo)");
        radioBtn_Prioridades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                radioBtn_PrioridadesMousePressed(evt);
            }
        });

        txt_quantumRR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_quantumRRKeyTyped(evt);
            }
        });

        textField_QuantumColaMedia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_QuantumColaMediaKeyTyped(evt);
            }
        });

        jLabel12.setText("Quantum:");

        jLabel13.setText("Cola de prioridad baja: (FCFS)");

        jLabel14.setText("Quantum:");

        textField_QuantumColaAlta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField_QuantumColaAltaKeyTyped(evt);
            }
        });

        jLabel15.setText("Cola de prioridad media: (Round Robin)");

        jLabel16.setText("Cola de prioridad alta: (Round Robin)");

        buttonGroup1.add(radioBtn_colasMultinivel);
        radioBtn_colasMultinivel.setText("Colas multinivel");
        radioBtn_colasMultinivel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                radioBtn_colasMultinivelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                radioBtn_colasMultinivelMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                radioBtn_colasMultinivelMouseExited(evt);
            }
        });

        buttonGroup1.add(jRadiobtn_sjf);
        jRadiobtn_sjf.setText("SJF");
        jRadiobtn_sjf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadiobtn_sjfMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAlgoritmosLayout = new javax.swing.GroupLayout(jPanelAlgoritmos);
        jPanelAlgoritmos.setLayout(jPanelAlgoritmosLayout);
        jPanelAlgoritmosLayout.setHorizontalGroup(
            jPanelAlgoritmosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlgoritmosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAlgoritmosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAlgoritmosLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(548, 548, 548))
                    .addGroup(jPanelAlgoritmosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanelAlgoritmosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioBtn_roundRobin)
                            .addComponent(radioBtn_fcfs)
                            .addComponent(radioBtn_Prioridades)
                            .addComponent(jRadiobtn_sjf)
                            .addComponent(radioBtn_colasMultinivel)
                            .addGroup(jPanelAlgoritmosLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanelAlgoritmosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelAlgoritmosLayout.createSequentialGroup()
                                        .addComponent(label_RR)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_quantumRR, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelAlgoritmosLayout.createSequentialGroup()
                                        .addGroup(jPanelAlgoritmosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel13))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelAlgoritmosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanelAlgoritmosLayout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textField_QuantumColaMedia))
                                            .addGroup(jPanelAlgoritmosLayout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textField_QuantumColaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(0, 548, Short.MAX_VALUE))))
        );
        jPanelAlgoritmosLayout.setVerticalGroup(
            jPanelAlgoritmosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlgoritmosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtn_fcfs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtn_roundRobin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAlgoritmosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_RR)
                    .addComponent(txt_quantumRR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtn_Prioridades)
                .addGap(18, 18, 18)
                .addComponent(jRadiobtn_sjf)
                .addGap(18, 18, 18)
                .addComponent(radioBtn_colasMultinivel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAlgoritmosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanelAlgoritmosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(textField_QuantumColaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelAlgoritmosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAlgoritmosLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel15))
                    .addGroup(jPanelAlgoritmosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(textField_QuantumColaMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(jLabel13)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jPanelTabs.addTab("Algoritmos", jPanelAlgoritmos);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.gray));
        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        tabla_procesos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Proceso", "Tamaño", "TA", "Ciclo de vida", "Prioridad", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_procesos.setToolTipText("");
        tabla_procesos.setDropMode(javax.swing.DropMode.INSERT_COLS);
        tabla_procesos.setFillsViewportHeight(true);
        tabla_procesos.setName("Procesos"); // NOI18N
        tabla_procesos.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(tabla_procesos);
        if (tabla_procesos.getColumnModel().getColumnCount() > 0) {
            tabla_procesos.getColumnModel().getColumn(0).setResizable(false);
            tabla_procesos.getColumnModel().getColumn(1).setResizable(false);
            tabla_procesos.getColumnModel().getColumn(2).setResizable(false);
            tabla_procesos.getColumnModel().getColumn(3).setResizable(false);
            tabla_procesos.getColumnModel().getColumn(4).setResizable(false);
            tabla_procesos.getColumnModel().getColumn(5).setResizable(false);
            tabla_procesos.getColumnModel().getColumn(5).setPreferredWidth(20);
        }

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jBtn_addProceso.setText("AGREGAR PROCESO");
        jBtn_addProceso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_addProcesoMouseClicked(evt);
            }
        });
        jBtn_addProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_addProcesoActionPerformed(evt);
            }
        });

        jLabel10.setText("Tamanio:");

        jLabel11.setText("Tiempo de arribo:");

        jLabel17.setText("Ciclo de vida:");

        jLabel18.setText("Prioridad: ");

        jTxt_tamanio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxt_tamanioKeyTyped(evt);
            }
        });

        jTxt_tiempoArribo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxt_tiempoArriboKeyTyped(evt);
            }
        });

        jTxt_cicloVida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_cicloVidaActionPerformed(evt);
            }
        });
        jTxt_cicloVida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxt_cicloVidaKeyTyped(evt);
            }
        });

        jBox_prioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BAJA", "MEDIA", "ALTA" }));

        jBtn_deleteRow.setText("ELIMINAR PROCESO");
        jBtn_deleteRow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_deleteRowMouseClicked(evt);
            }
        });
        jBtn_deleteRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_deleteRowActionPerformed(evt);
            }
        });

        btn_modificar.setText("MODIFICAR PROCESO");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton1.setText("SELECCIONAR PROCESO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelProcesosLayout = new javax.swing.GroupLayout(jPanelProcesos);
        jPanelProcesos.setLayout(jPanelProcesosLayout);
        jPanelProcesosLayout.setHorizontalGroup(
            jPanelProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProcesosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBox_prioridad, 0, 90, Short.MAX_VALUE)
                    .addComponent(jTxt_cicloVida)
                    .addComponent(jTxt_tamanio)
                    .addComponent(jTxt_tiempoArribo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtn_addProceso, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(jBtn_deleteRow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelProcesosLayout.setVerticalGroup(
            jPanelProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProcesosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelProcesosLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                        .addGap(31, 31, 31))
                    .addGroup(jPanelProcesosLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanelProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanelProcesosLayout.createSequentialGroup()
                                    .addGroup(jPanelProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(jTxt_tamanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(19, 19, 19)
                                    .addGroup(jPanelProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(jTxt_tiempoArribo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanelProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel17)
                                        .addComponent(jTxt_cicloVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(22, 22, 22)
                                    .addGroup(jPanelProcesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel18)
                                        .addComponent(jBox_prioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jSeparator1))
                            .addGroup(jPanelProcesosLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jBtn_addProceso)
                                .addGap(18, 18, 18)
                                .addComponent(btn_modificar)
                                .addGap(18, 18, 18)
                                .addComponent(jBtn_deleteRow)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanelTabs.addTab("Procesos", jPanelProcesos);

        jMenuBar1.setToolTipText("");

        jMenu_Archivo.setText("Archivo");
        jMenuBar1.add(jMenu_Archivo);

        jMenu2.setText("Editar");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTabs))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTabs)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tamMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamMemoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tamMemoriaActionPerformed
    
    int idPart = 0;
    int dirIni = 0;
    
    private void btn_addParticionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addParticionActionPerformed
        
        
        idPart = idPart +1;
        
        if (check_part()){
          ptm.removeRow(idPart);
        }
        
        part[0] = idPart;
        part[1] = Integer.parseInt(tamMemoria.getText());
        part[2] = dirIni + 1;
        
        if (idPart == 1){
            dirIni = 0;
            part[2] = 0;
        }
        
        dirIni = dirIni + Integer.parseInt(tamParticion.getText());
        
        ptm.addRow(part); /* agrega la particion */
        limpiar(); /* limpia los txt field */
        
        
        
    }//GEN-LAST:event_btn_addParticionActionPerformed

    private void radiobtn_variablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtn_variablesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtn_variablesActionPerformed

    private void radiobtn_fijasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtn_fijasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtn_fijasActionPerformed

    private void radiobtn_firstfitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtn_firstfitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtn_firstfitActionPerformed

    private void tamParticionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamParticionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tamParticionActionPerformed

    private void radioBtn_fcfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtn_fcfsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtn_fcfsActionPerformed

    private void tamMemoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tamMemoriaKeyTyped
        char c = evt.getKeyChar(); if (c<'0'||c>'9') evt.consume();
        
    }//GEN-LAST:event_tamMemoriaKeyTyped

    private void tamParticionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tamParticionKeyTyped
        char c = evt.getKeyChar(); if (c<'0'||c>'9') evt.consume();
    }//GEN-LAST:event_tamParticionKeyTyped

    private void txt_quantumRRKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_quantumRRKeyTyped
        char c = evt.getKeyChar(); if (c<'0'||c>'9') evt.consume();
    }//GEN-LAST:event_txt_quantumRRKeyTyped

    private void textField_QuantumColaAltaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_QuantumColaAltaKeyTyped
        char c = evt.getKeyChar(); if (c<'0'||c>'9') evt.consume();
    }//GEN-LAST:event_textField_QuantumColaAltaKeyTyped

    private void textField_QuantumColaMediaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_QuantumColaMediaKeyTyped
        char c = evt.getKeyChar(); if (c<'0'||c>'9') evt.consume();
    }//GEN-LAST:event_textField_QuantumColaMediaKeyTyped

    private void btn_addParticionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addParticionMouseClicked
        
    }//GEN-LAST:event_btn_addParticionMouseClicked

    private void btn_addParticionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_addParticionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addParticionKeyTyped

    private void jTxt_cicloVidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_cicloVidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_cicloVidaActionPerformed

    private void jTxt_tamanioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_tamanioKeyTyped
        char c = evt.getKeyChar(); if (c<'0'||c>'9') evt.consume();
    }//GEN-LAST:event_jTxt_tamanioKeyTyped

    private void jTxt_tiempoArriboKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_tiempoArriboKeyTyped
        char c = evt.getKeyChar(); if (c<'0'||c>'9') evt.consume();
    }//GEN-LAST:event_jTxt_tiempoArriboKeyTyped

    private void jTxt_cicloVidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_cicloVidaKeyTyped
        char c = evt.getKeyChar(); if (c<'0'||c>'9') evt.consume();
    }//GEN-LAST:event_jTxt_cicloVidaKeyTyped

    private void jBtn_addProcesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_addProcesoMouseClicked
         
    }//GEN-LAST:event_jBtn_addProcesoMouseClicked

    private void jBtn_deleteRowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_deleteRowMouseClicked

    }//GEN-LAST:event_jBtn_deleteRowMouseClicked

    private void jBtn_deleteRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_deleteRowActionPerformed
         /* Accion al presionar Eliminar Proceso (deberia eliminarlo de la tabla de 
        procesos) */
        
        if (tabla_procesos.getSelectedRow() != -1){
            dtm.removeRow(tabla_procesos.getSelectedRow());
        } else {
            JOptionPane.showMessageDialog(null, "No ha seleccionado ningun proceso"
                    + "","Atencion",JOptionPane.INFORMATION_MESSAGE);
        }
            
    }//GEN-LAST:event_jBtn_deleteRowActionPerformed
        
    int item = 0;
    
    
    private void jBtn_addProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_addProcesoActionPerformed
        /* Accion al presionar Agregar Proceso (deberia agregarlo a la tabla de 
        procesos) */
        
        if (check()){
          dtm.removeRow(item);
        }
        
        item = item + 1;
        
        
        o[0] = String.valueOf(item);
        o[1] = jTxt_tamanio.getText();
        o[2] = jTxt_tiempoArribo.getText();
        o[3] = jTxt_cicloVida.getText();
        o[4] = jBox_prioridad.getSelectedItem();
        
        dtm.addRow(o);
        limpiar();
        
        
    }//GEN-LAST:event_jBtn_addProcesoActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
         /* Accion al presionar Modificar Proceso (deberia modificarlo en la tabla de 
        procesos) */
        
        if (filaSeleccionada != -1){
            tabla_procesos.setValueAt(jTxt_tamanio.getText(), filaSeleccionada, 1);
            tabla_procesos.setValueAt(jTxt_tiempoArribo.getText(), filaSeleccionada, 2);
            tabla_procesos.setValueAt(jTxt_cicloVida.getText(), filaSeleccionada, 3);
            tabla_procesos.setValueAt(jBox_prioridad.getSelectedItem(), filaSeleccionada, 4);
            limpiar();
            filaSeleccionada = -1;
        } else {
            JOptionPane.showMessageDialog(this, "No se cargo campos", "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        filaSeleccionada = tabla_procesos.getSelectedRow();
        if (filaSeleccionada != -1) {
            limpiar();
            jTxt_tamanio.setText(tabla_procesos.getValueAt(filaSeleccionada, 1).toString());
            jTxt_tiempoArribo.setText(tabla_procesos.getValueAt(filaSeleccionada, 2).toString());
            jTxt_cicloVida.setText(tabla_procesos.getValueAt(filaSeleccionada, 3).toString());
        } else {
            JOptionPane.showMessageDialog(null, "No has seleccinado una fila");
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void radioBtn_roundRobinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioBtn_roundRobinMousePressed
        txt_quantumRR.setEnabled(true);
        textField_QuantumColaAlta.setEnabled(false);
        textField_QuantumColaMedia.setEnabled(false);
    }//GEN-LAST:event_radioBtn_roundRobinMousePressed

    private void radioBtn_roundRobinMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioBtn_roundRobinMouseReleased

    }//GEN-LAST:event_radioBtn_roundRobinMouseReleased

    private void radioBtn_colasMultinivelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioBtn_colasMultinivelMousePressed
        textField_QuantumColaAlta.setEnabled(true);
        textField_QuantumColaMedia.setEnabled(true);
        txt_quantumRR.setEnabled(false);
    }//GEN-LAST:event_radioBtn_colasMultinivelMousePressed

    private void radioBtn_colasMultinivelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioBtn_colasMultinivelMouseReleased
    }//GEN-LAST:event_radioBtn_colasMultinivelMouseReleased

    private void radioBtn_colasMultinivelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioBtn_colasMultinivelMouseExited
    }//GEN-LAST:event_radioBtn_colasMultinivelMouseExited

    private void radioBtn_fcfsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioBtn_fcfsMousePressed
        textField_QuantumColaAlta.setEnabled(false);
        textField_QuantumColaMedia.setEnabled(false);
        txt_quantumRR.setEnabled(false);
    }//GEN-LAST:event_radioBtn_fcfsMousePressed

    private void radioBtn_PrioridadesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioBtn_PrioridadesMousePressed
        textField_QuantumColaAlta.setEnabled(false);
        textField_QuantumColaMedia.setEnabled(false);
        txt_quantumRR.setEnabled(false);
    }//GEN-LAST:event_radioBtn_PrioridadesMousePressed

    private void jRadiobtn_sjfMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadiobtn_sjfMousePressed
        textField_QuantumColaAlta.setEnabled(false);
        textField_QuantumColaMedia.setEnabled(false);
        txt_quantumRR.setEnabled(false);
    }//GEN-LAST:event_jRadiobtn_sjfMousePressed
    
    private void limpiar(){
        jTxt_tamanio.setText("");
        jTxt_tiempoArribo.setText("");
        jTxt_cicloVida.setText("");
        tamMemoria.setText("");
        tamParticion.setText("");
    }
    
    private boolean check(){
        if ((jTxt_tamanio.getText().length() == 0) || ( jTxt_tiempoArribo.getText().length() == 0 ) ||
                (jTxt_cicloVida.getText().length() == 0)){
                JOptionPane.showMessageDialog(this, "No dejar campos Vacíos", "Error!", JOptionPane.ERROR_MESSAGE);
                return true;
        } else {
            return false;
        }    
    }
    
    private boolean check_part(){
        if ((tamMemoria.getText().length() == 0) || ( tamParticion.getText().length() == 0 )){
                JOptionPane.showMessageDialog(this, "No dejar campos Vacíos", "Error!", JOptionPane.ERROR_MESSAGE);
                return true;
        } else {
            return false;
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_addParticion;
    private javax.swing.JButton btn_modificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    public static javax.swing.JComboBox<String> jBox_prioridad;
    public static javax.swing.JButton jBtn_addProceso;
    public static javax.swing.JButton jBtn_deleteRow;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_tamparticion;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_Archivo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelAlgoritmos;
    private javax.swing.JPanel jPanelMemoria;
    private javax.swing.JPanel jPanelProcesos;
    public static javax.swing.JTabbedPane jPanelTabs;
    public static javax.swing.JRadioButton jRadiobtn_sjf;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTextField jTxt_cicloVida;
    public static javax.swing.JTextField jTxt_tamanio;
    public static javax.swing.JTextField jTxt_tiempoArribo;
    private javax.swing.JLabel label_RR;
    public static javax.swing.JPanel panej_gantt;
    private javax.swing.JPanel panel_configuracionMemoria;
    public static javax.swing.JRadioButton radioBtn_Prioridades;
    public static javax.swing.JRadioButton radioBtn_colasMultinivel;
    public static javax.swing.JRadioButton radioBtn_fcfs;
    public static javax.swing.JRadioButton radioBtn_roundRobin;
    public static javax.swing.JRadioButton radiobtn_bestfit;
    public static javax.swing.JRadioButton radiobtn_fijas;
    public static javax.swing.JRadioButton radiobtn_firstfit;
    public static javax.swing.JRadioButton radiobtn_variables;
    public static javax.swing.JRadioButton radiobtn_worstfit;
    public static javax.swing.JTable tabla_particiones;
    public static javax.swing.JTable tabla_procesos;
    public static javax.swing.JTextField tamMemoria;
    public static javax.swing.JTextField tamParticion;
    public static javax.swing.JTextField textField_QuantumColaAlta;
    public static javax.swing.JTextField textField_QuantumColaMedia;
    public static javax.swing.JTextField txt_quantumRR;
    // End of variables declaration//GEN-END:variables
}
